/* Generated by the Nim Compiler v2.0.2 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
import { el } from "@elemaudio/core" 
var c_553648130 = el.div(el.add(el.cycle(440.0), el.cycle(441.0)), el.const({value: 2.0, key: "divisor"}));
var channels_553648131 = [c_553648130, c_553648130];
export {channels_553648131 as channels}
